[supervisord]
nodaemon=true
user=root
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:artifactdepot]
command=python3 -m uvicorn artifactdepot.main:app --host 0.0.0.0 --port 8004
directory=/app/artifactdepot/src
environment=PYTHONPATH="/app/artifactdepot/src"
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/artifactdepot.out.log
